spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none

    generate-ddl: false

  application:
    name: "BoilerplateSpring"
