spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:onboarding;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;
    username: test
    password: test
